CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bubbleId` varchar(64),
	`clientUserId` int,
	`bubbleClientId` varchar(64),
	`bubbleClientCompanyId` varchar(64),
	`description` text,
	`slug` varchar(256),
	`requestStatus` varchar(64),
	`status` varchar(64),
	`dateType` varchar(32),
	`startDate` timestamp,
	`endDate` timestamp,
	`locationAddress` text,
	`locationLat` varchar(32),
	`locationLng` varchar(32),
	`isHourly` boolean DEFAULT true,
	`openRate` boolean DEFAULT false,
	`artistHourlyRate` int,
	`clientHourlyRate` int,
	`ages` text,
	`direct` boolean DEFAULT false,
	`sentToNetwork` boolean DEFAULT false,
	`transportation` boolean DEFAULT false,
	`converted` boolean DEFAULT false,
	`masterServiceTypeId` varchar(64),
	`clientEmail` varchar(320),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`bubbleCreatedAt` timestamp,
	`bubbleModifiedAt` timestamp,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobs_bubbleId_unique` UNIQUE(`bubbleId`)
);
