CREATE TABLE `interested_artists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bubbleId` varchar(64),
	`jobId` int,
	`bubbleRequestId` varchar(64),
	`artistUserId` int,
	`bubbleArtistId` varchar(64),
	`clientUserId` int,
	`bubbleClientId` varchar(64),
	`bubbleServiceId` varchar(64),
	`bubbleBookingId` varchar(64),
	`status` varchar(64),
	`converted` boolean DEFAULT false,
	`isHourlyRate` boolean DEFAULT true,
	`artistHourlyRate` int,
	`clientHourlyRate` int,
	`artistFlatRate` int,
	`clientFlatRate` int,
	`totalHours` int,
	`startDate` timestamp,
	`endDate` timestamp,
	`resumeLink` text,
	`message` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`bubbleCreatedAt` timestamp,
	`bubbleModifiedAt` timestamp,
	CONSTRAINT `interested_artists_id` PRIMARY KEY(`id`),
	CONSTRAINT `interested_artists_bubbleId_unique` UNIQUE(`bubbleId`)
);
