CREATE TABLE `bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bubbleId` varchar(64),
	`jobId` int,
	`bubbleRequestId` varchar(64),
	`interestedArtistId` int,
	`bubbleInterestedArtistId` varchar(64),
	`clientUserId` int,
	`bubbleClientId` varchar(64),
	`artistUserId` int,
	`bubbleArtistId` varchar(64),
	`bookingStatus` varchar(64),
	`paymentStatus` varchar(64),
	`clientRate` int,
	`artistRate` int,
	`totalClientRate` int,
	`totalArtistRate` int,
	`grossProfit` int,
	`stripeFee` int,
	`postFeeRevenue` int,
	`hours` int,
	`externalPayment` boolean DEFAULT false,
	`startDate` timestamp,
	`endDate` timestamp,
	`locationAddress` text,
	`locationLat` varchar(32),
	`locationLng` varchar(32),
	`description` text,
	`stripeCheckoutUrl` text,
	`addedToSpreadsheet` boolean DEFAULT false,
	`deleted` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`bubbleCreatedAt` timestamp,
	`bubbleModifiedAt` timestamp,
	CONSTRAINT `bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `bookings_bubbleId_unique` UNIQUE(`bubbleId`)
);
