CREATE TABLE `leads_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brevoId` int,
	`email` varchar(320) NOT NULL,
	`emailBlacklisted` boolean DEFAULT false,
	`firstName` varchar(128),
	`lastName` varchar(128),
	`fullName` varchar(256),
	`companyName` varchar(256),
	`city` varchar(256),
	`state` varchar(128),
	`country` varchar(128),
	`brevoUserRole` varchar(64),
	`hiringCategory` varchar(128),
	`brevoListIds` text,
	`totalCampaignsReceived` int DEFAULT 0,
	`totalOpens` int DEFAULT 0,
	`totalClicks` int DEFAULT 0,
	`lastOpenedAt` timestamp,
	`lastClickedAt` timestamp,
	`lastCampaignAt` timestamp,
	`hasUnsubscribed` boolean DEFAULT false,
	`artswrkUserId` int,
	`isArtswrkUser` boolean DEFAULT false,
	`artswrkUserRole` varchar(32),
	`artswrkHiringCategory` varchar(128),
	`jobsPostedCount` int DEFAULT 0,
	`bookingCount` int DEFAULT 0,
	`artswrkPro` boolean DEFAULT false,
	`artswrkBasic` boolean DEFAULT false,
	`clientPremium` boolean DEFAULT false,
	`lastSyncedAt` timestamp NOT NULL DEFAULT (now()),
	`brevoCreatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_contacts_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_contacts_brevoId_unique` UNIQUE(`brevoId`),
	CONSTRAINT `leads_contacts_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `leads_sync_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`syncType` enum('full','stats') NOT NULL DEFAULT 'full',
	`contactsUpserted` int DEFAULT 0,
	`artswrkMatched` int DEFAULT 0,
	`error` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `leads_sync_log_id` PRIMARY KEY(`id`)
);
